### ISSUE TITLE
Windows 11 0S Build 26100.1150 is not available

### ISSUE THREAD

**Issue by huanglin-github** [ExplorerPatcher/ep_taskbar_releases#1]
![1](https://github.com/user-attachments/assets/e6b31fce-bc6a-4a54-96db-c356976501d1)
![2](https://github.com/user-attachments/assets/e8b32b2f-6c82-48fa-bba5-c5037850d0dd)

**Comment by Amrsatrio** [comment]
Wrong DLL. Get the ep_taskbar.5.dll one.
